Doxygen doc update for heat_transfer.h
lethe-cfd/lethe pull request #1034
Opened 2024-02-12 19:35 UTC by mivaia

# Description of the problem

- Doxygen documentation incomplete for heat_transfer.h

# Description of the solution

- Updated it

# How Has This Been Tested?

- Web verification. 

# Comments

- First PR.
- Part of Doxygen documentation hackathon.

2024-02-12 22:50 UTC, blaisb requested changes
Some small changes. Nothing big, but some of these comments are very verbose lets say :)

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> + * rho * Cp * (dT/dt + u.gradT) = k div(gradT) + nu/rho * (gradu : gradu)
```suggestion
 * \f$ \rho * C_p * (\frac{dT}{dt} + u \cdot \nabla T) = k \nabla^2T + \tau : \nabla u \f$
```
You should write the documentation using LaTeX format.

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> + * k \cdot \nabla^2 T + \frac{\nu}{\rho} \cdot (\nabla u : \nabla u) \f$
```suggestion
 * k \cdot \nabla^2 T + \tau : \nabla u \f$
```

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * the Parameters::PhysicsID int enum.
```suggestion
   * @param multiphysics_interface Map of the auxiliary physics that will be
   * solved on top of a computational fluid dynamic simulation. 
```

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
>    assemble_nitsche_heat_restriction(bool assemble_matrix);
```suggestion
  assemble_nitsche_heat_restriction(const bool assemble_matrix);
```
Good opportunity to make this a const :)

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * @return The point at which the evaluation is performed.
```suggestion
   * @return The vector at which the evaluation is performed.
```

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * in \f$ u^{n+1} = u^n + \alpha ^n \delta u ^n \f$. Where \f$ \alpha ^n \f$
That's maybe a lot of information. The Newton solver should contain the details regarding the Newton update itself :)

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * @param domain_name Btring indicating the monitored_fluid in the console output,
```suggestion
   * @param domain_name String indicating the monitored_fluid in the console output,
```

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * used for mesh_refinement and simulation restarts.
I don't think this needs this much detail here, but if you feel like it does, why not

2024-02-12 22:50 UTC, blaisb commented on include/solvers/heat_transfer.h
> +   * but for solutions at previous time steps.
You already said it above, so here I would not repeat myself.

2024-02-14 16:19 UTC, oguevremont reviewed
Nice PR!

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * related to time stepping and the stopping criterions.
```suggestion
   * related to time stepping and the stopping criteria.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @param assemble_matrix boolean that is true for matrix assembly, and false for rhs assembly.
```suggestion
   * @param assemble_matrix Boolean that is true for matrix assembly, and false for rhs assembly.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Allow Heat Transfer to set-up solution vector from checkpoint file.
```suggestion
   * @brief Allow Heat Transfer to set up solution vector from checkpoint file.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Set-up the DofHandler and the degree of freedom associated with the physics.
```suggestion
   * @brief Set up the DofHandler and the degrees of freedom associated with the physics.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Set-up the initial conditions associated with the physics.
```suggestion
   * @brief Set up the initial conditions associated with the physics.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Set-up the vector of assembler functions
```suggestion
   * @brief Set up the vector of assembler functions
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Prepare Heat Transfer to write checkpoint
```suggestion
   * @brief Prepare Heat Transfer to write checkpoint.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * Generally, physics only support imposing nodal values, but some physics
I would put this comment in Auxiliary Physics and write specifically what Heat Transfer allows as initial conditions.

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * strategy appropriate to the auxiliary physics.
Same comment here for specificity, if you agree.

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @return Right hand side vector
```suggestion
   * @return Right hand side vector.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Post-processing. Write the liquid fraction to an output file
```suggestion
   * @brief Post-processing. Write the liquid fraction to an output file.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * stopping criterion. See simulation_control abstract class for more
```suggestion
   * stopping criteria. See simulation_control abstract class for more
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Is a transformation which maps point in the reference cell to
```suggestion
   * @brief Transformation which maps point in the reference cell to
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * points and summing the point values with specific weights
```suggestion
   * points and summing the point values with specific weights.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * points and summing the point values with specific weights
```suggestion
   * points and summing the point values with specific weights.
```

2024-02-14 16:19 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * locally_owned_dofs and the DoF indices on all ghost cells.
```suggestion
   * locally_owned_dofs and the DoF indices on ghost cells.
```

2024-02-20 14:16 UTC, blaisb commented
Is this ready for a re-review?

2024-02-22 16:09 UTC, mivaia commented
> Is this ready for a re-review?

Yess it is!

2024-02-23 16:37 UTC, oguevremont approved these changes

2024-02-23 16:37 UTC, oguevremont commented on include/solvers/heat_transfer.h
> +   * @brief Constructor of the HeatTransfer object
```suggestion
   * @brief Constructor of the HeatTransfer object.
```

2024-02-23 20:25 UTC, blaisb approved these changes

2024-02-24 16:15 UTC, merged