Add the example on turbulent taylor-couette flow
lethe-cfd/lethe pull request #1083
Opened 2024-03-31 02:52 UTC by blaisb

# Description of the problem

- Using the Matrix Free solver, Joel cooked up a very cool 3d Taylor-Couette example that really showcases the power of the matrix free approach

# Description of the solution

- To keep this example for the future, we add it as an example test case.

# How Has This Been Tested?

- Runs well, this is super chill.

2024-04-01 20:15 UTC, PierreLaurentinCS requested changes
Very cool example featuring the power of matrix-free Lethe. I've put minor comments here and there but overall it's a very good job!

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    #Recovering datas
```suggestion
    #Recovering data
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    #Stocking datas
```suggestion
    #Loading data
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    """Function that retrieves and returns, in the form of arrays, the time and adimensional kinetic energy values obtained during simulation.
```suggestion
    """Function that retrieves and returns, in the form of arrays, the time and dimensionless kinetic energy values obtained during simulation.  
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    #Adimensionnal factor
```suggestion
    #Dimensionless factor
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +            - d = Annulus width (re-ri)
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +            - d = Annulus width (re-ri)
No inputs for this function

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    Sortie (Dans l'ordre énuméré ci-dessous) :
```suggestion
    Outputs (same order as below):
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    #Recovering datas
```suggestion
    #Recovering data
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    coeff = (2*d*d)/(rho*U*U)
This dimensionless coefficient seems to have a dimension of s^2.m^3/kg

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-functions.py
> +    #Stocking datas
```suggestion
    #Loading data
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +  set number mesh adapt = 0
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +  set number mesh adapt = 0
It's a default parameter

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +  set output frequency                 = 1
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +  set kinetic energy name              = kinetic_energy
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +  set enstrophy name                   = enstrophy
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
> +end
```suggestion
```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-postprocessing.py
> +### Simulations datas ###
```suggestion
### Simulations data ###

```

2024-04-01 20:15 UTC, PierreLaurentinCS commented on examples/incompressible-flow/3d-turbulent-taylor-couette/tc-postprocessing.py
> +#enstrophy
```suggestion
#Enstrophy

```

2024-04-02 14:24 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +  E_k &= \frac{1}{\Omega} \int_{\Omega} \frac{\mathbf{u}\cdot \mathbf{u}}{2} \mathrm{d}\Omega \\
Yeah I understand, it's the kinetic energy per unit of mass and volume. It's the definition we use in the regular Lethe doc which I agree is maybe not the most adequate. If we change that I'd change it in another PR however.

2024-04-02 14:25 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +Rest of the Subsections
lolz

2024-04-02 14:26 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +
I'll need to re-run the simulations which will be a bit difficult to do remotely for now, but I can keep this in mind and fix it in a future PR

2024-04-02 14:34 UTC, lpsaavedra commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +   p &= \frac{1}{2}A^2r^2 + 2AB\ln(r) - \frac{\frac{1}{2}B^2}{r^2} + \frac{1}{2}(\epsilon U)^2 \cos(2\theta) \sin(\frac{2(r-r_i)\pi}{r_i}) \sin(\frac{2z}{d})
```suggestion
.. math::
   u_{\theta} &= Ar + \frac{B}{r} + \epsilon U\sin(\theta) \sin \left( \frac{(r-r_i)\pi}{r_i} \right) \sin \left( \frac{z}{d} \right) \\
   u_{r} &= \epsilon U\cos(\theta) \sin \left( \frac{(r-r_i)\pi}{r_i} \right) \sin \left( \frac{z}{d} \right) \\
   u_{z} &= 0 \\
   p &= \frac{1}{2}A^2r^2 + 2AB\ln(r) - \frac{\frac{1}{2}B^2}{r^2} + \frac{1}{2}(\epsilon U)^2 \cos(2\theta) \sin  \left( \frac{2(r-r_i)\pi}{r_i} \right) \sin \left( \frac{2z}{d} \right)
```

2024-04-03 09:22 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +  The mesh resolution used in the case study consists of 20 radial elements, 80 azimuthal elements, and 64 axial elements totalling 102,400 elements. Additionally, it incorporates a mesh refinement n
```suggestion
  The mesh resolution used in the case study consists of 20 radial elements, 80 azimuthal elements, and 64 axial elements totalling 102,400 elements.  
```

2024-04-03 09:22 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
> +
I fixed this now

2024-04-03 09:23 UTC, blaisb commented
I applied all of your comments @PierreLaurentinCS so if you are ok with it I will merge

2024-04-03 13:55 UTC, PierreLaurentinCS approved these changes
All good !

2024-04-04 08:52 UTC, merged