Change image + small fixes
lethe-cfd/lethe pull request #377
Opened 2022-01-22 22:02 UTC by jeannejoachim

# Description of the problem

- first image had no background and so it was not readable in dark mode
- some small typo here and there

# Description of the solution

- Fixing it all

# Documentation

examples/multiphysics/warming-up-a-viscous-fluid : 
- warming-up-a-viscous-fluid.rst
- images/warming_scheme.pgn

2022-01-23 20:12 UTC, lpsaavedra requested changes
Nice example. However, I think it still needs some work before getting merged:

- Add the sections that are missing: features, location of the example, description, the different sections of the parameter file, running the simulation and possibilities for extensions.
- Add the ^\circ before the C for celsius whenever it is written in math mode (line 219 of the main file)

In addition, I wonder why the multiphysics dam-break-VOF example is there but not added in the multiphysics.rst. Is there any particular reason for that? We may need to create an additional PR to fix this. Also there is a warning regarding a help_from_2D_to_2D file that was added in the cfd.rst but it does not exits. Is this a WIP?

2022-01-24 13:32 UTC, blaisb commented
> In addition, I wonder why the multiphysics dam-break-VOF example is there but not added in the multiphysics.rst. Is there any particular reason for that? 

There is no reason for that, it's a mistake in the original PR we did not catch.

2022-01-24 13:48 UTC, lpsaavedra commented
> There is no reason for that, it's a mistake in the original PR we did not catch.

OK, then in that case I will create an additional PR to add it

2022-01-24 16:05 UTC, CaroleAnneDaunais approved these changes

2022-01-24 21:22 UTC, jeannejoachim commented on doc/source/parameters/cfd/cfd.rst
> +   help_from_2D_to_2D
it's a WIP in another branch, I don't know that it was added there so I will remove it ^^"

2022-01-24 21:24 UTC, jeannejoachim commented
> Nice example. However, I think it still needs some work before getting merged:
> 
>     * Add the sections that are missing: features, location of the example, description, the different sections of the parameter file, running the simulation and possibilities for extensions.
> 
>     * Add the ^\circ before the C for celsius whenever it is written in math mode (line 219 of the main file)

You are right, this PR is a good occasion of reviewing this example and make it in the same fashion as the others! I did not have this in mind (I just wanted to change the first figure), but I can definitely do that now!

2022-01-25 01:51 UTC, lpsaavedra commented
Seems good to me now Jeanne! The example looks amazing and it has all the sections that we have in other examples. I will only quickly fix some warnings that were generated and then it should be ready to merge!

2022-01-25 01:58 UTC, lpsaavedra reviewed
Seems good to me now Jeanne! The example looks amazing and it has all the sections that we have in other examples. I will quickly fix some warnings that were generated and then it should be ready to merge after correcting this small typo

2022-01-25 01:58 UTC, lpsaavedra commented on doc/source/examples/multiphysics/warming-up-a-viscous-fluid/warming-up-a-viscous-fluid.rst
> +* See how the **resolution order** (``velocity order``, ``pressure order`` and ``temperature order``) affects the precision with reguards to the analytical solution.
```suggestion
* Test a **different time integration scheme** and see if there is any difference in the computational cost and/or the precision with regards to the analytical solution.
* See how the **resolution order** (``velocity order``, ``pressure order`` and ``temperature order``) affects the precision with regards to the analytical solution.
```

2022-01-25 02:05 UTC, lpsaavedra approved these changes

2022-01-25 02:06 UTC, blaisb approved these changes
Just two small comments.

2022-01-25 02:06 UTC, blaisb commented on doc/source/examples/multiphysics/warming-up-a-viscous-fluid/warming-up-a-viscous-fluid.rst
>      Heat transfer phenomenon occur at a much larger characteristic time than fluid transport phenomenon. To reach a stable state for the system, the end time much be quite big, but the time step can
```suggestion
    Heat transfer phenomenon occur at a much larger characteristic time than fluid transport phenomenon. To reach a stable state for the system, the end time much be quite big, but the time step can also be increased (in the limit of numerical stability).
```

2022-01-25 02:06 UTC, blaisb commented on doc/source/examples/multiphysics/warming-up-a-viscous-fluid/warming-up-a-viscous-fluid.rst
>      As the fluid velocity is not influences by heat transfer (one-way coupling), the fluid velocity will remain constant for the whole simulation across the domain, and as heat transfer occurs at a l
```suggestion
    As the fluid velocity is not influenced by heat transfer (one-way coupling), the fluid velocity will remain constant for the whole simulation across the domain, and as heat transfer occurs at a larger scale, the mesh can be coarse.
```

2022-01-25 15:40 UTC, jeannejoachim commented
Done! Thank you @lpsaavedra for fixing the warnings, I learned something :)

2022-01-25 15:49 UTC, merged