Cell void fraction test
lethe-cfd/lethe pull request #463
Opened 2022-04-25 22:12 UTC by voferreira

# Description of the problem

- Void fraction used to calculate the void fraction applied in drag models was always the interpolated one.
- We would like to test the cell void fraction instead

# Description of the solution

- Created a variable in the scratch data to store the void fraction of each cell
- Changed the name of the interpolated void fraction to 'interpolated_void_fraction'
- Created a parameter to control whether the void fraction used to calculate drag is the cell one or the interpolated at the particle's position

# How Has This Been Tested?

- Sedimentation of a single particle.

# Documentation

- [ ] Unresolved CFD-DEM parameters guide

2022-04-25 23:42 UTC, blaisb requested changes
This is a good implementation, but i think there is an easier solution. The issue I have with this current implementation is that every new drag model will require to take this if condition into account. I think it might be better to store the void_fraction for each particle in the reinit differently depending on this switch. If this switch is true, then you store the interpolated void fraction. if it's false, then you store the constant void fraction (but still in a vector). Thus, every force model will see the new void fraction model no matter what is the implementation. This will be easier to maintain in the long term. We can talk about it tomorrow if you want :)!

2022-04-26 14:14 UTC, shahabgol approved these changes

2022-04-26 14:45 UTC, voferreira commented on source/fem-dem/parameters_cfd_dem.cc
> +      "true",
The non interpolated one is a test. The original implementation uses the interpolated one.

2022-04-26 15:08 UTC, tonielgeitani approved these changes

2022-04-26 15:08 UTC, tonielgeitani commented on source/fem-dem/parameters_cfd_dem.cc
> +      "Choose whether the void fraction is the one of the cell or the interpolated at the particle position.");
```suggestion
      "Choose whether the void fraction is the one of the cell or the one interpolated at the particle position.");
```

2022-04-26 15:14 UTC, tonielgeitani commented on source/solvers/navier_stokes_scratch_data.cc
> +  cell_void_fraction = double(n_global_max_particles_per_cell);
This line should be defined the same way you define the interpolated_void_fraction as:
cell_void_fraction =
     std::vector<double>(n_global_max_particles_per_cell);

2022-04-26 15:49 UTC, blaisb requested changes
One last tiny thing to change. Good work.

2022-04-26 19:40 UTC, blaisb approved these changes

2022-04-27 22:20 UTC, merged