add loagrangian postprocessing to cfd-dem
lethe-cfd/lethe pull request #473
Opened 2022-05-06 20:13 UTC by tonielgeitani

# Description of the problem

-The current PCM void fraction scheme is discontinuous in time. This limits its accuracy and applicability to certain sizes of the mesh. We propose a new method to circumvent these limitations

# Description of the solution

- Added a new void fraction scheme that solves the discontinuity in time of the PCM method. However, this new method has a limitation which is that it behaves as the PCM at the boundaries and is therefore non continuous only at the boundaries.
- Added the average_velocity_magnitude to the lagrangian post processing function. 
- Added a particle property which is the particle's contribution to the overall volume of the particles. It is needed for the new void fraction scheme to normalize the void fraction as it is necessary for mass conservation.

# How Has This Been Tested?

-No test has been created for this new scheme. As it is a large PR, once everything is cleared, a test can be added for this feature.
-Note that the cfd-dem tests are failing for the master dealii in Debug mode.

# Documentation

- The documentation will be created once everything is cleared and all tests passes

# Future changes

- The new void fraction scheme test along with the documentation changes would be implemented in a small PR after this PR is approved with all current changes

2022-05-07 23:13 UTC, shahabgol reviewed
Good work. I have a few minor comments.

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                particle_properties[DEM::PropertiesIndex::dp] / 2;
```suggestion
                particle_properties[DEM::PropertiesIndex::dp] * 0.5;
```

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                  double R = 0;
```suggestion
                  double R = 0.0;
```

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                              [DEM::PropertiesIndex::contribution] += 0;
what does this line mean? += 0

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                            particle_properties[DEM::PropertiesIndex::dp] / 2;
```suggestion
                            particle_properties[DEM::PropertiesIndex::dp] * 0.5;
```

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                            particles_volume_in_sphere += 0;
the same comment as above

2022-05-07 23:13 UTC, shahabgol commented on source/fem-dem/gls_vans.cc
> +                                    (pow(r_particle, 2) *
I suggest adding these calculations for 2d and 3d into two separate functions and calling the functions (here and above).

2022-05-08 16:06 UTC, blaisb requested changes
Some things to address, but I have yet to find why your tests are failing. I'll look more into it.

2022-05-08 16:06 UTC, blaisb commented on source/fem-dem/gls_vans.cc
> +    particle_handler.exchange_ghost_particles(true);
I don't think this needs to be in this if. In all cases, it would be a good idea to always exchange ghost particles when starting the simulation.

2022-05-09 14:05 UTC, tonielgeitani commented on source/fem-dem/gls_vans.cc
> +                              [DEM::PropertiesIndex::contribution] += 0;
absolutely nothing

2022-05-09 21:22 UTC, tonielgeitani commented
All review comments have been addressed

2022-05-13 00:36 UTC, blaisb commented
@tonielgeitani I think you just need to resolve the conflict and update the documentation and this will be ready for a merge :)!

2022-05-14 11:46 UTC, blaisb approved these changes

2022-05-15 19:19 UTC, blaisb commented
I think this will be ready for a merge soon. Could you modify the documentation in the .rst to ensure that the new option is described? @lpsaavedra or @CaroleAnneDaunais will be able to finalize the merge thereafter. :)

2022-05-16 16:24 UTC, lpsaavedra commented
I think this is now ready to be merged. Do you agree @shahabgol?

2022-05-16 19:23 UTC, merged