Ribbon gls example
lethe-cfd/lethe pull request #546
Opened 2022-08-02 17:29 UTC by AmishgaAlphonius

A new "Ribbon Mixer using a Single Rotating Reference Frame" example was created.

# Comments

- Should we add a "Velocity Source" page in the _Parameter Guide_ for the "Velocity Source" subsection used in this example?

2022-08-02 19:13 UTC, CaroleAnneDaunais reviewed
Nice example! The Compute Canada manipulations are cleverly reported. This is going to be very helpful for everyone! :)

2022-08-02 19:13 UTC, CaroleAnneDaunais commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +In reality, the velocity field and its streamlines are visualized in an Eulerian frame. It is possible to do so by simply selecting ``velocity_eulerian`` in Paraview.
```suggestion
In the reference frame of the tank, the velocity field and its streamlines are visualized in an Eulerian frame. It is possible to do so by simply selecting ``velocity_eulerian`` in Paraview.
```

2022-08-02 21:59 UTC, blaisb commented
@AmishgaAlphonius I would add the velocity source to the RST
Will gladly review PR tomorrow

2022-08-02 22:00 UTC, blaisb commented
I also suggest you rebase, will make the CI simpler

2022-08-03 03:01 UTC, blaisb requested changes
Very minor comments. Good @AmishgaAlphonius !!!!

2022-08-03 03:01 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +As we can see in the image above, for :math:`Re < 10` (laminar regime), the Lethe curve fits well with the experimental values.
```suggestion
As we can see in the image above, for :math:`Re < 100` (laminar regime), the Lethe curve fits well with the experimental values.
```

2022-08-03 03:01 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +References
I would add a possibility for extension to suggest simulating it at a higher Reynolds number in a transient simulation and compare with the experimental data :).

2022-08-03 13:35 UTC, AmishgaAlphonius commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +- Use of a Digital Research Alliance of Canada (Alliance) cluster to run simulations
I think the idea behind it was to let readers know that this is a first example where we go through step-by-step on how to launch simulations on a cluster and then retrieve the results from it. I might be interpreting the "Features" section wrong.

2022-08-03 14:15 UTC, AmishgaAlphonius commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +    N_p = \frac{2 \pi \Gamma}{\rho N^2 D^5}
I've moved it up :)

2022-08-03 14:35 UTC, AmishgaAlphonius commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +Using ``lethe_case_generator.py``, we generate the :math:`25` cases with :math:`Re` ranging from :math:`0.1` to :math:`100`. Before running the Python script, it is important to **specify your group
I've added a few sentences, can you see if it's okay?

2022-08-03 14:35 UTC, AmishgaAlphonius commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +Here are a few examples of other job directives you may want to specify in your job script:
I've added a "warning", can you see if it's okay?

2022-08-03 14:44 UTC, blaisb commented on doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
> +- Use of a Digital Research Alliance of Canada (Alliance) cluster to run simulations
Nah your interpretation is correct. I did not see it that way initially, but it's a good idea :)

2022-08-04 13:30 UTC, ghazalemir reviewed
Amishga,
I went through the example and also Carole-Anne and Bruno's comments; I had very minimal comments more than what they commented on
Good job for explaining all necessary details.

2022-08-04 13:37 UTC, blaisb commented
@AmishgaAlphonius I added the Navier-Stokes equation in a rotating frame of reference :).

2022-08-04 13:38 UTC, CaroleAnneDaunais approved these changes

2022-08-04 14:09 UTC, blaisb approved these changes

2022-08-04 14:09 UTC, blaisb commented on doc/source/parameters/cfd/velocity_source.rst
> +This subsection allows you to change the reference frame of the calculated velocity in a given system. This is especially useful when it is easier to solve a problem in a Lagrangian reference frame.
```suggestion
This subsection allows you to defined velocity-dependant source term. At the moment, this used to solve a problems in a Lagrangian reference frame for which the Coriolis and centrifugal forces must be added.
```

2022-08-05 01:45 UTC, merged