Add thermal post-processing to nitsche IB
lethe-cfd/lethe pull request #678
Opened 2023-01-05 16:11 UTC by blaisb

# Description of the problem

- The nitsche beta heat coefficient for heat transfer was scaled with the mesh size. This enabled good dirichlet boundary conditions but made it difficult to carry industrial analysis with it. 
- There was no way to post-process the heat extracted by the Nitsche IB

# Description of the solution

- The beta heat coefficient is now mesh independent. This parameter now has a physical meaning, it is the heat extracted W/m^2 (in 2D) or W/m^3 in 3D
- The nitsche heat flux is now post-processed when other heat fluxes are calculated.

# How Has This Been Tested?

- A new test has been added to validate this approach

# Documentation

-  Documentation has been modified accordingly

2023-01-05 19:30 UTC, jeannejoachim requested changes
Neat implementation, I like that it is already general to multiple solids, well done (and so fast!).

There are few dead bodies remaining and a mistake on the output name that should be fixed before merging.

Also I am not sure if it is better to have multiple output files or only one `heat_flux_table` with more column. I would prefer the later to centralize the information and remove parameters that are not too useful IMHO, but in the end it's up to you.

Finally, could you add clarification on the `beta heat` parameter of the nitsche documentation page? It would be good to add its physical meaning, dimensions and to link it to the Boundary Conditions - Multiphysics / heat transfer (I can add that to this PR, tell me if I should).

Thanks :)

2023-01-05 19:30 UTC, jeannejoachim commented on source/solvers/heat_transfer.cc
> +        "bc_" + Utilities::int_to_string(i_solid, 1),
```suggestion
        "solid_" + Utilities::int_to_string(i_solid, 1),
```

2023-01-05 19:30 UTC, jeannejoachim commented on source/solvers/heat_transfer.cc
> +HeatTransfer<dim>::postprocess_heat_flux_on_nitsche_ib()
very neat method!

2023-01-05 19:30 UTC, jeannejoachim commented on source/solvers/heat_transfer.cc
> +                  double      temperature = 0;
Could be good to specify the variable name for future readers (`fluid_temperature` or `temperature_fluid`)

2023-01-05 19:30 UTC, jeannejoachim commented on source/solvers/heat_transfer.cc
> +                  // Calculate heat flux on the Nitsche IB
```suggestion
                  // Calculate heat flux on the fluid at the Nitsche IB
```

2023-01-05 19:30 UTC, jeannejoachim commented on source/solvers/heat_transfer.cc
> +      this->pcout << "Heat flux on nitsche immersed boundary : " << std::endl;
```suggestion
      this->pcout << "Heat flux at the nitsche immersed boundary : " << std::endl;
```

2023-01-05 19:30 UTC, jeannejoachim commented on doc/source/parameters/cfd/post_processing.rst
> +    * ``nitsche flux name``: output filename for heat flux calculations on a Nitsche immersed boundary
Maybe add a link to the documentation
```suggestion
    * ``nitsche flux name``: output filename for heat flux calculations on a Nitsche immersed boundary.
    
      .. warning ::
      
          Do not forget to ``set enable heat boundary condition = true`` in the :doc:`nitsche` subsection of the ``.prm``.
      
```

2023-01-05 20:06 UTC, blaisb commented on applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_moving.output
> +1024  1.022915e-05
Because the mathematical definition of beta has changed, hence the results have also changed.

2023-01-05 20:07 UTC, blaisb commented on applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_static.output
> +1024  8.342655e-05
Because the mathematical definition of beta has changed, hence the results have also changed.

2023-01-05 20:07 UTC, blaisb commented on source/solvers/heat_transfer.cc
> +  //                 specific_heat_model->value(field_values);
I'd rather keep it in comment form for a few months should we have the need to impose actual Dirichlet BC using the Nitsche method on the thermal side.

2023-01-05 20:08 UTC, blaisb commented on source/solvers/heat_transfer.cc
> +                                penalty_parameter * beta *
I'd rather keep it if we eventually want to support both the flux version or the dirichlet version of the Nitsche thermal BC.

2023-01-07 04:56 UTC, jeannejoachim approved these changes
@blaisb You will want to review it, on my side I may still have to fix minor output on a few tests but then it is good to go.

2023-01-07 17:50 UTC, blaisb commented on applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_couette.output
> +	 Nitsche boundary 0 : 1000
agreed, sound idea

2023-01-07 17:51 UTC, blaisb reviewed
Very good changes. Thanks! That really makes the model more useable

2023-01-08 14:38 UTC, blaisb commented
@jeannejoachim Everything looks good to me.  Is it ready for merge on your side?

2023-01-08 18:57 UTC, jeannejoachim commented
> @jeannejoachim Everything looks good to me. Is it ready for merge on your side?

Yes all good for me too :) Huge kudo Bruno for your help!

2023-01-08 21:41 UTC, merged