Clear the tangential overlap after load balancing in DEM
lethe-cfd/lethe pull request #797
Opened 2023-07-12 13:54 UTC by acdaigneault

# Description of the problem

- Tangential overlap and relative velocity stored values in contact info object were lost during load balancing only for contacts of particles that is moved on other processor.
- Disabling contacts algorithm had a small glitch after load balancing because the identification of the mobility status was not executed at the right place (before exchange of ghost).

# Description of the solution
- Force the resetting of the tangential overlap and relative velocity values during the update of the iterator since it loops on the map of the contact info object. It used the `load_balance_step` boolean to trigger this resetting.
- Move the identification of the mobility after the exchange of ghost particles

2023-07-12 14:45 UTC, blaisb commented
@acdaigneault some tests don't seem to work anymore?

2023-07-12 15:04 UTC, blaisb requested changes
Tiny naming changes, nothing significant.

2023-07-12 15:04 UTC, blaisb commented on include/dem/update_local_particle_containers.h
> +  const bool load_balance_step = false);
Is load balance_step the right variable name here or should it be "clear_contact_structures" In essence, the fact that we clear when we load balance is one thing, but the action being asked of the structure is to clear it.

2023-07-12 15:04 UTC, blaisb commented on source/dem/update_local_particle_containers.cc
> +                  if (load_balance_step)
I would definitely call that variable "clear"

2023-07-12 21:21 UTC, blaisb commented
Awesome, will merge after CI

2023-07-13 01:09 UTC, blaisb commented on source/dem/update_local_particle_containers.cc
> +                      // Update the particle id of the particle in contact
Is this comment still valid? I am not sure it makes sense no? (or it should apply to the line above no?)

2023-07-13 01:09 UTC, blaisb approved these changes
One last thing to check and it will be ok to merge

2023-07-13 14:24 UTC, acdaigneault commented on source/dem/update_local_particle_containers.cc
> +                      // Update the particle id of the particle in contact
```suggestion
```

2023-07-13 19:13 UTC, merged