Mesh controler
lethe-cfd/lethe pull request #801
Opened 2023-07-12 21:09 UTC by Luckabarbeau

# Description of the problem

- The maximal number of elements is not always taken into consideration correctly.
- We have no way to control the exact number of elements in the domain.

# Description of the solution

-Create a mesh refinement controller that controls the number of elements in the domain to be equal to the maximal number of elements.

# How Has This Been Tested?

- Multiple examples have been run with this enables.
- Creating a test with it would be very costly since multiple time steps are needed.

# Documentation

- The new parameters have been added.

2023-07-13 14:07 UTC, oguevremont commented on include/core/mesh_controller.h
> + * controller is use to define the coarsening factor.
```suggestion
 * controller is used to define the coarsening factor.
```

2023-07-13 14:08 UTC, oguevremont commented on include/core/mesh_controller.h
> +  // Function that return the coarsening factor.
```suggestion
/**
* @brief Returns the coarsening factor.
*/
```

2023-07-13 14:10 UTC, oguevremont commented on include/core/mesh_controller.h
> +  // Constructor with the number of elements
```suggestion
/**
* @brief Constructor
* @param target_number_of_elements
*/
```

2023-07-13 14:11 UTC, oguevremont commented on source/core/mesh_controller.cc
> +
```suggestion
```

2023-07-13 14:11 UTC, oguevremont commented on source/core/mesh_controller.cc
> +MeshController::calculate_coarsening_factor(int current_number_of_cell)
To change with refactor
```suggestion
MeshController::calculate_coarsening_factor(int current_number_of_cells)
```

2023-07-13 14:13 UTC, oguevremont commented on source/solvers/navier_stokes_base.cc
> +  // Override the maximal number of element if the controller is use.
```suggestion
  // Override the maximal number of element if the controller is used.
```

2023-07-13 14:14 UTC, oguevremont commented on source/solvers/navier_stokes_base.cc
> +    maximal_number_of_element = INT_MAX;
```suggestion
    maximal_number_of_element = std::numeric_limits<int>::max();
```

2023-07-13 14:21 UTC, oguevremont commented
An idea for the future, but if it becomes necessary we could add P, I and D parameters, but given them default values like the one that are currently hard-coded.

2023-07-13 14:32 UTC, hepap commented on source/core/mesh_controller.cc
> +  double D = 0.1;
Will these parameters always work (i.e., could it be interesting to add them in the .prm)?

2023-07-13 14:32 UTC, hepap commented on source/solvers/navier_stokes_base.cc
> +  unsigned int maximal_number_of_element =
```suggestion
  unsigned int maximal_number_of_elements =
```

2023-07-13 16:03 UTC, oguevremont approved these changes

2023-07-13 16:03 UTC, oguevremont commented on doc/source/parameters/cfd/mesh_adaptation_control.rst
> +    If the ``fraction refinement`` parameter is too high, the controller may not be able to maintain the number of elements constant. If ``fraction type = number``, the maximal ``fraction refinement`
Alright, I didn't understand it well before

2023-07-13 16:41 UTC, blaisb requested changes
Some changes there and there. It would be great to have a unit test for the feature though.

2023-07-13 16:41 UTC, blaisb commented on doc/source/parameters/cfd/mesh_adaptation_control.rst
> +	  set fraction type                     = number
Are those characters tabs? We moved away from using tabs in the .rst file it breaks on some renderers. Can you double check that there are no tabs?

2023-07-13 16:41 UTC, blaisb commented on doc/source/parameters/cfd/mesh_adaptation_control.rst
> +* The boolean parameter ``enable mesh refinement controller`` activates a controller that overrides the value of the of ``fraction coarsening`` parameter. If activated, the controller will try to mai
```suggestion
* The boolean parameter ``enable mesh refinement controller`` activates a controller that overrides the value of the of ``fraction coarsening`` parameter. If activated, the controller will try to maintain the total number of elements in the domain equal to the value of ``max number elements`` parameter. The control is done using a PID controller.
```
Is it a PID or a PI?

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> +* Author: Lucka, Polytechnique Montreal, 2023 -
```suggestion
```
We moved away from using author names in the files.

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> + */
use @class when writing the brief for the class

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> +   * @param target_number_of_elements
More verbose comments please

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> +  MeshController(int target_number_of_elements)
```suggestion
  MeshController(const unsigned int target_number_of_elements)
```

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> +  calculate_coarsening_factor(int current_number_of_elements);
```suggestion
  calculate_coarsening_factor(const unsigned int current_number_of_elements);
```

2023-07-13 16:41 UTC, blaisb commented on include/core/mesh_controller.h
> +  int       previous_number_of_elements;
```suggestion
  const unsigned int target_number_of_elements;
  unsigned int       previous_number_of_elements;
```

2023-07-13 16:41 UTC, blaisb commented on source/core/CMakeLists.txt
> +  mesh_controller.cc
Please put file in alphabetical order

2023-07-13 16:41 UTC, blaisb commented on source/core/CMakeLists.txt
> +  ../../include/core/mesh_controller.h)
Not could, but should

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +{
Can you write a unit test for this class

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +using namespace std;
```suggestion
```
Let's avoid these namespace. We don't have that in the library (or we should not)

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +                 (double)target_number_of_elements;
```suggestion
                 (double)target_number_of_elements;
```
Should be a static_cast<double>

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +    (double)target_number_of_elements;
static cast

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +        }
```suggestion
      if (error > 0.0)
          previous_mesh_control_error = previous_mesh_control_error - error;
```

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +        {
```suggestion
```

2023-07-13 16:41 UTC, blaisb commented on source/core/mesh_controller.cc
> +        }
```suggestion
```

2023-07-13 16:41 UTC, blaisb commented on source/core/parameters.cc
> +        "enable mesh refinement controller",
I concur. I would also remove the enable. It's a booleann, so if it's true it's enabled

2023-07-14 00:47 UTC, blaisb approved these changes
Just 1-2 Small comments left to address

2023-07-14 00:47 UTC, blaisb commented on include/core/mesh_controller.h
> +* Author: Lucka, Polytechnique Montreal, 2023 -
Stil needs to be removed

2023-07-14 00:47 UTC, blaisb commented on source/core/mesh_controller.cc
> +  double error = static_cast<signed int>(target_number_of_elements -
```suggestion
  double error = static_cast<double>(target_number_of_elements -
```

2023-07-14 00:47 UTC, blaisb commented on source/core/mesh_controller.cc
> +  double previous_error = static_cast<signed int>(target_number_of_elements -
```suggestion
  double previous_error = static_cast<double>(target_number_of_elements -
```

2023-07-14 00:47 UTC, blaisb commented on source/solvers/navier_stokes_base.cc
> +  double coarsening_factor = mesh_controller.calculate_coarsening_factor(
```suggestion
  const double coarsening_factor = mesh_controller.calculate_coarsening_factor(
```

if it's not modified afterwards

2023-07-14 00:47 UTC, blaisb commented on source/solvers/navier_stokes_base.cc
> +  unsigned int maximal_number_of_elements =
```suggestion
  const unsigned int maximal_number_of_elements =
```
If its not modified afterwards

2023-07-14 01:39 UTC, Luckabarbeau commented on source/solvers/navier_stokes_base.cc
> +  unsigned int maximal_number_of_elements =
this is not a const

2023-07-14 01:45 UTC, blaisb commented
@Luckabarbeau Awesome, will merge after CI

2023-07-14 11:17 UTC, blaisb commented
@Luckabarbeau it seems your test is not portable?

2023-07-14 16:04 UTC, merged