Deprecate SDIRK time integrators
lethe-cfd/lethe pull request #839
Opened 2023-08-09 19:10 UTC by blaisb

# Description of the problem

- The SDIRK time integrators were poorly maintained and gave a false illusion that they were actually useable in contexts in which they were not.
-  No one was actually using the time integrators and they have worse performance than the equivalent BDF one

# Description of the solution

- Remove the SDIRK integrator. If we actually need them in the future, we can do a better reimplementation.

# Documentation

- Updated documentation

2023-08-09 19:30 UTC, lpsaavedra commented on include/solvers/navier_stokes_base.h
> -  std::vector<VectorType> solution_stages;
I think all the multiphysics solvers have this parameter as well and needs to be deleted? Cahn Hilliard, VOF, heat transfer, tracer?

2023-08-09 19:36 UTC, oguevremont reviewed
Good! Some questions/comments, but nothing major

2023-08-09 19:36 UTC, oguevremont commented on include/core/sdirk.h
Are we keeping some lines, just in case?

2023-08-09 19:36 UTC, oguevremont commented on source/core/parameters.cc
>          method = TimeSteppingMethod::bdf3;
Sdirk options are still in the declare_parameters explanatory text, they should be removed

2023-08-09 19:36 UTC, oguevremont commented on source/fem-dem/gls_sharp_navier_stokes.cc
There is still #include <core/sdirk.h>, maybe it needs to be removed. It is also in other files

2023-08-09 19:52 UTC, lpsaavedra requested changes
Some questions/comments need to be addressed before merging. Also, there are two places in the documentation where sdirk is still mentioned and this should be updated:

- [x] `/doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst` line 304.
- [ ] `/doc/source/examples/sharp-immersed-boundary-solver/sedimentation-1-particle/sedimentation-1-particle.rst` line 64.

2023-08-09 19:52 UTC, lpsaavedra commented on include/solvers/navier_stokes_base.h
> -  std::vector<VectorType> solution_stages;
I think all the multiphysics (heat transfer, tracer, vof and cahn hilliard) and it should be removed as well?

2023-08-09 19:52 UTC, lpsaavedra commented on source/core/parameters.cc
In this file, sdirk options need to be removed when declaring the parameters of simulation control (between lines 61 and 70)...

2023-08-09 19:52 UTC, lpsaavedra commented on source/solvers/cahn_hilliard_scratch_data.cc
Related to my comment above: `cahn_hilliard_scratch_data.h` still uses solution_stages in several places

2023-08-09 19:52 UTC, lpsaavedra commented on source/solvers/heat_transfer_scratch_data.cc
Related to my comment above: `heat_transfer_scratch_data.h` still uses solution_stages in several places

2023-08-09 19:52 UTC, lpsaavedra commented on source/solvers/tracer_scratch_data.cc
Related to my comment above: `tracer_scratch_data.h` still uses solution_stages in several places

2023-08-09 19:52 UTC, lpsaavedra commented on source/solvers/vof_scratch_data.cc
Related to my comment above: vof_scratch_data.h still uses solution_stages in several places

2023-08-09 19:52 UTC, lpsaavedra commented on include/core/sdirk.h
Do we still want to have `sdirk.h` and `sdirk.cc` in `source/core/CMakeLists.txt`? We could remove it if it is not being used. We should also avoid including the file if not used (remove the `#include <core/sdirk.h>` from all files) in source solvers.

2023-08-09 20:59 UTC, blaisb commented on include/core/sdirk.h
Yeah I'd rather leave the file for the coefficients, but not use it anymore. I'll clean that up.

2023-08-10 09:49 UTC, lpsaavedra approved these changes
Seems good to me! Only two minor additional changes: the #include directive should be removed also from: `vans_assemblers.cc` and `gls_sharp_navier_stokes.cc`.

2023-08-10 11:35 UTC, blaisb commented
> Seems good to me! Only two minor additional changes: the #include directive should be removed also from: `vans_assemblers.cc` and `gls_sharp_navier_stokes.cc`.

Done! I'll merge after CI :)

2023-08-10 12:44 UTC, oguevremont approved these changes

2023-08-10 18:15 UTC, merged