Add dimension to missing files
lethe-cfd/lethe pull request #878
Opened 2023-09-14 19:49 UTC by voferreira

# Description of the problem

- Some `prm` files did not have `dimension` yet. 
- AESTHETIC ONLY: Some `Simulation Control` lines were `Simulation and IO Control`. @AmishgaAlphonius and I do not like it.

# Description of the solution

- Fixed it.

# How Has This Been Tested?

- Generators were tested

2023-09-14 21:28 UTC, AmishgaAlphonius requested changes
Nice work! I'm happy to see that it is all more uniform now :)
There were just a few upper delimiter lines missing for the ``Simulation Control`` header in some ``.prm`` and I had 2 more comments:
- [x] In DEM application tests, ``applications_tests/dem/insert_plane_3d.prm`` has a header for dimension, whereas other files don't. It could therefore be removed.
- [x] Also, ``applications_tests/dem/insert_list_3d_default_velocities.prm`` still has some spaces after the ``#`` in the header delimeter lines. (I am not sure if you were planning on doing it in this PR or another one ^^')

2023-09-14 21:28 UTC, AmishgaAlphonius commented on performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic.prm
>  #---------------------------------------------------
```suggestion
#----------------------

set dimension = 3

#---------------------------------------------------
```

2023-09-14 21:28 UTC, AmishgaAlphonius commented on performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic_load_balancing.prm
>  #---------------------------------------------------
```suggestion
#----------------------

set dimension = 3

#---------------------------------------------------
```

2023-09-14 22:25 UTC, AmishgaAlphonius approved these changes

2023-09-15 11:01 UTC, blaisb approved these changes

2023-09-15 11:01 UTC, merged