Free angle ch
lethe-cfd/lethe pull request #879
Opened 2023-09-14 20:33 UTC by PierreLaurentinCS

# Description of the problem

- 1 : For some specific problem, the angle of contact should not be specified which leaves one more term to solve in the assembly on the boundary. 
- 2 : No tool was available to compute the barycenter of one fluid in a multiphase simulations in the Cahn-Hilliard solver

# Description of the solution

- 1: A new free_angle boundary condition was added to the model for this to be solved.
- 2:  A new tool allowing to compute the barycenter of an object was added for Cahn-Hilliard simulations. This was useful for the rising bubble case.

# How Has This Been Tested?

- The barycenter function was used to compare the rising bubbles using Cahn-Hilliard ans VOF. Its usage will be demonstrated in a subsequent PR

# Documentation

- Boundary conditions multiphysics (boundary_conditions_multiphysics.rst) ans post-processing (post_processing.rst) sections were updated.

# Comments

- Anything that you want to add up that didn't fit in any other category can be written here

2023-09-15 15:41 UTC, AmishgaAlphonius requested changes
Nice work! :)
I have a few comments and suggestions here and there.

2023-09-18 18:37 UTC, voferreira requested changes
Nice! I have some suggestions here and there but mostly cosmetics. Good job, Pierre!

2023-09-18 18:37 UTC, voferreira commented on source/solvers/cahn_hilliard.cc
> +              std::cout << "+------------------------------------------+"
You could use  announce_string from utilities.h here. It is merely cosmetic, but eventually someone will need to change it if you do not implement in this version.

2023-09-18 18:37 UTC, voferreira commented on source/solvers/cahn_hilliard.cc
> +
```suggestion
```

2023-09-18 18:37 UTC, voferreira commented on source/solvers/cahn_hilliard_assemblers.cc
> +                              local_matrix(i, j) +=
```suggestion
                              local_matrix(i, j) -=
```

2023-09-18 18:37 UTC, voferreira commented on source/solvers/cahn_hilliard_assemblers.cc
> +                                -epsilon * epsilon * phi_potential_i *
```suggestion
                                epsilon * epsilon * phi_potential_i *
```

2023-09-19 19:05 UTC, voferreira requested changes
@PierreLaurentinCS For the reasons we talked about, I am requesting changes again to make sure the rebasing procedure does not break the master branch on merging.

2023-09-19 20:13 UTC, AmishgaAlphonius reviewed
Last few comments :)

2023-09-19 20:13 UTC, AmishgaAlphonius commented on include/core/parameters.h
> +    // Prefix for the vof and Cahn-Hilliard barycenter output
```suggestion
    // Prefix for the VOF and Cahn-Hilliard barycenter output
```

2023-09-19 20:13 UTC, AmishgaAlphonius commented on source/core/parameters.cc
> +        "Name of barycenter information output file in VOF or Cahn-Hilliard= simulations");
```suggestion
        "Name of barycenter information output file in VOF or Cahn-Hilliard simulations");
```

2023-09-19 20:13 UTC, AmishgaAlphonius commented on source/core/parameters.cc
> +        "Enable calculation of the barycenter location and velocity of the fluid 1 in VOF and Cahn-Hilliard simulations.");
```suggestion
        "Enable calculation of the barycenter location and velocity of fluid 1 in VOF and Cahn-Hilliard simulations.");
```

2023-09-19 21:43 UTC, voferreira commented on source/solvers/cahn_hilliard.cc
> +      this->pcout << "Phase statistics: " << std::endl;
You could use the announce string with "-" as separator here to look like the VANS results.

2023-09-19 21:44 UTC, voferreira commented on source/solvers/cahn_hilliard.cc
> +      this->pcout << "Phase statistics: " << std::endl;
The results could be left aligned as well.

2023-09-19 21:44 UTC, voferreira commented on source/solvers/cahn_hilliard.cc
> +      this->pcout << "\t Integral: " << integral << std::endl;
Additionally, add a line at the end for fashion.

2023-09-19 21:46 UTC, voferreira approved these changes
Nothing else to say :)

2023-09-19 22:06 UTC, AmishgaAlphonius approved these changes
Looks good to me also :)

2023-09-21 13:02 UTC, merged