Compile with C++20
lethe-cfd/lethe pull request #912
Opened 2023-10-21 16:16 UTC by peterrum

# Description of the problem

- Code does not compile with C++20.

# Description of the solution

- Fix some namespaces.
- Fix some constructors.
- Fix one implicit capturing of a lambda function.

# How Has This Been Tested?

# Documentation

# Future changes

There are still some warning that need to be fixed:

```
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc: In instantiation of ‘void GLSSharpNavierStokesSolver<dim>::load_particles_from_file() [with int dim = 2]’:
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4643:16:   required from here
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4339:41: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4339 |           if (restart_data["type"][p_i] == Shape<dim>::ShapeType::sphere)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4345:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4345 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4354:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4354 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4414:41: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4414 |           if (restart_data["type"][p_i] == Shape<dim>::ShapeType::sphere)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4420:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4420 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4430:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4430 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4439:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4439 |           else if (restart_data["type"][p_i] == Shape<dim>::ShapeType::torus)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4446:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4446 |           else if (restart_data["type"][p_i] == Shape<dim>::ShapeType::cone)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4453:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4453 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4463:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4463 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4472:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<2>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4472 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc: In instantiation of ‘void GLSSharpNavierStokesSolver<dim>::load_particles_from_file() [with int dim = 3]’:
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4644:16:   required from here
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4339:41: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4339 |           if (restart_data["type"][p_i] == Shape<dim>::ShapeType::sphere)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4345:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4345 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4354:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4354 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4414:41: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4414 |           if (restart_data["type"][p_i] == Shape<dim>::ShapeType::sphere)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4420:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4420 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4430:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4430 |           else if (restart_data["type"][p_i] ==
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4439:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4439 |           else if (restart_data["type"][p_i] == Shape<dim>::ShapeType::torus)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4446:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} with enumeration type ‘Shape<3>::ShapeType’ is deprecated [-Wdeprecated-enum-float-conversion]
 4446 |           else if (restart_data["type"][p_i] == Shape<dim>::ShapeType::cone)
/home/munch/sw-p3/lethe/source/fem-dem/gls_sharp_navier_stokes.cc:4453:46: warning: comparison of floating-point type ‘__gnu_cxx::__alloc_traits<std::alloc [...]

2023-10-21 17:03 UTC, blaisb approved these changes

2023-10-21 17:04 UTC, blaisb commented
Thanks @peterrum . I had never tried to compile it with C++20 enabled yet. Great catch. I'll look into the warnings later on this week/next week.

2023-10-21 17:06 UTC, blaisb requested changes
@peterrum It seems that the this you added in the lambda function prevents compilation on the CI.
It seems that forked PR currently don't allow for our PUSH CI to fully function. I'll double check that.

2023-10-22 11:50 UTC, peterrum commented
@blaisb I have reverted the change to the lambda function, since it is only a warning:

```
/home/munch/sw-p3/lethe/source/rpt/particle_detector_interactions.cc: In lambda function:
/home/munch/sw-p3/lethe/source/rpt/particle_detector_interactions.cc:188:12: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
  188 |   auto F = [=](double t) {
      |            ^
/home/munch/sw-p3/lethe/source/rpt/particle_detector_interactions.cc:188:12: note: add explicit ‘this’ or ‘*this’ capture
```

2023-10-23 10:48 UTC, blaisb commented
Worked on my machine, so I will merge.

2023-10-23 10:48 UTC, blaisb approved these changes

2023-10-23 10:54 UTC, merged