Checkpoint missing tables
lethe-cfd/lethe pull request #938
Opened 2023-11-27 13:42 UTC by AmishgaAlphonius

# Description of the problem

- A few tables were omitted from being _"checkpointed"_ causing a lost of valuable information when simulations were restarted (Issue: #916).

# Description of the solution

- The missing have been added to the `write_checkpoint()` and `read_checkpoint()` of each physic.

# How Has This Been Tested?

- Waiting for CI
- Restart application-tests were updated:
  - [ ] `applications_tests/lethe-fluid/cavity_ht_average_velocity_restart`
  - [ ] `applications_tests/lethe-fluid/mms-transient-conduction-restart_gls`
  - [ ] `applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1`

# Documentation

- A small correction was made to `doc/source/parameters/cfd/restart.rst`

2023-11-27 16:52 UTC, blaisb requested changes
A quick question. I'll try finishing the review of the rest ASAP

2023-11-27 21:09 UTC, blaisb approved these changes
Just one line to remove and it should be good :)

2023-11-27 21:09 UTC, blaisb commented on include/core/utilities.h
> +#include <deal.II/base/convergence_table.h>
```suggestion
```

2023-11-28 02:52 UTC, oguevremont approved these changes

2023-11-28 02:52 UTC, oguevremont commented on source/solvers/heat_transfer.cc
> +    }
Is it intended that there are not `{}` for the first if, but that there are for the other two?

2023-11-28 02:52 UTC, oguevremont commented on source/solvers/heat_transfer.cc
> +    }
Same question here

2023-11-28 02:53 UTC, oguevremont commented on source/solvers/heat_transfer.cc
> +    }
I saw this a few times and it was always consistent, so not a problem unless you prefer to change it

2023-11-28 17:15 UTC, merged