Add heat flux postprocessor
lethe-cfd/lethe pull request #953
Opened 2023-12-06 23:15 UTC by mivaia

# Description of the problem

- In the context of conjugated heat transfer simulations, there was no way to get the local heat fluxes of the domain.

# Description of the solution

- A new `DataPostprocessorVector` child class was made, namely, `HeatFluxPostprocessor`. This class postprocesses the local heat fluxes of the fluids and solids of the domain. The values for each fluid and solid is outputed individually.

# How Has This Been Tested?

- CI

2023-12-07 02:29 UTC, oguevremont approved these changes
Very minor comments, good work! After my suggestions it is approved

2023-12-07 02:29 UTC, oguevremont commented on source/solvers/heat_transfer.cc
> +                            .physical_properties_manager.get_number_of_solids();
```suggestion
  const unsigned int n_fluids = this->simulation_parameters
                            .physical_properties_manager.get_number_of_fluids();
  const unsigned int n_solids = this->simulation_parameters
                            .physical_properties_manager.get_number_of_solids();
```

2023-12-07 02:29 UTC, oguevremont commented on include/solvers/postprocessors.h
> +  virtual void
```suggestion
  {}
  
  virtual void
```

2023-12-07 18:34 UTC, blaisb requested changes
Minor minor changes, but please add a bit more comments

2023-12-07 19:33 UTC, hepap reviewed
Nice addition! I agree with Bruno that a bit more comments would help :) Also, may be you can add a test to verify your implementation? I don't know if it is relevant at this point, but a pseudo 1D case with different layers of different materials could be interesting (there are analytical solutions for that in the BSL I think!)

2023-12-08 19:05 UTC, AmishgaAlphonius approved these changes

2023-12-08 19:16 UTC, blaisb approved these changes

2023-12-08 19:16 UTC, merged